### ISSUE TITLE
Lion XProtect.plist

### ISSUE THREAD

**Issue by alvarnell** [melomac/XPlist#1]
Apple seems to have taken down the Lion page:
http://configuration.apple.com/configurations/macosx/xprotect/2/clientConfiguration.plist

I suppose that's because with OS X 10.7.5 with Security Update 2014-003 uses the Mountain Lion page.  I recommend changing the Lion url to:
http://configuration.apple.com/configurations/macosx/xprotect/3/clientConfiguration.plist

**Comment by melomac** [comment]
Thank you for reporting this issue.

It turns out the URL seems alive today:
```
$ curl -I http://configuration.apple.com/configurations/macosx/xprotect/2/clientConfiguration.plist 
HTTP/1.1 200 OK
Server: Apache
Last-Modified: Fri, 29 Sep 2017 20:20:52 GMT
ETag: "181a0-55a59c2e6a51b"
Accept-Ranges: bytes
Content-Length: 98720
Content-Type: text/plain
Content-Language: en-us
Cache-Control: max-age=58
Expires: Sat, 14 Oct 2017 13:20:28 GMT
Date: Sat, 14 Oct 2017 13:19:30 GMT
Connection: keep-alive
```

**Comment by alvarnell** [comment]
Sorry that I failed to update this. It was only down for one update.

But the other part of my comment stands. Everybody that with a fully up-to-date Lion installation, to include Security Update 2014-003 receives the Mountain Lion version. Only those who are running an Lion without the update receive the older XProtect version.
